Centralized logic

diff --git a/bin/db-snapshot b/bin/db-snapshot
--- a/bin/db-snapshot
+++ b/bin/db-snapshot
@@ -5,10 +5,30 @@ bin=$(dirname "$0")
 
 if [ "${3}" = "--help" ]; then
   echo "SYNTAX: ${COLOR_LIGHT_BLUE}db snapshot [server shortname]${COLOR_NC}"
-  echo "Tries to connect to the provided database server"
+  echo "Makes a snapshot of the database at the provided database server"
   exit 1
 fi
 
+msg=${3}
+
+shift 2
+
+ts=$(date +%Y%m%d-%H%M%S)
+
+if [ -z "${msg}" ]; then
+  filename=${ts}
+else
+  filename=${ts}-${msg}
+  shift
+fi
+file="${dumps}/${filename}.gz"
+
 echo "${colored_shortname}"
-"${bin}/drivers/${databasetype}/connectors/${connectiontype}/snapshot" "$@"
-exit $?
+"${bin}/drivers/${databasetype}/connectors/${connectiontype}/snapshot" "${project_root}" "${identifier}" "${file}" "$@"
+code=$?
+
+if [ "${code}" -eq 1 ]; then
+  echo "${COLOR_RED}Could not make snapshot of database.${COLOR_NC}"
+else
+  echo "${COLOR_GREEN}Successfully made snapshot of database.${COLOR_NC}"
+fi
