Adjusted to work with new structure

diff --git a/bin/drivers/mysql/connectors/ssh/snapshot b/bin/drivers/mysql/connectors/ssh/snapshot
--- a/bin/drivers/mysql/connectors/ssh/snapshot
+++ b/bin/drivers/mysql/connectors/ssh/snapshot
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
 
-bin=$(dirname "$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]+"/../../.."))' $0)")
+bin=$(dirname "$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]+"/../../../.."))' $0)")
 . "${bin}/include/all"
 
 shortname=${2}
@@ -19,19 +19,20 @@ database=$(cat "${database_file}")
 options="--opt -B --add-drop-database"
 connection_details="--defaults-extra-file=${connection_config}"
 
+where=$(cat "${ssh_config}")
+_user=$(cat "${connection_config}" | grep "^user" | cut -d '=' -f 2 | xargs)
+_pass=$(cat "${connection_config}" | grep "^password" | cut -d '=' -f 2 | xargs)
+_host=$(cat "${connection_config}" | grep "^host" | cut -d '=' -f 2 | xargs)
 
-_config="${repository}/${shortname}/config/"
-_credentials="${_config}credentials.cnf"
-_ssh_config="${_config}/ssh.cnf"
-_db_file="${_config}/database"
 
-where=$(cat "${_ssh_config}")
-_user=$(cat "${_credentials}" | grep "^user" | cut -d '=' -f 2 | xargs)
-_pass=$(cat "${_credentials}" | grep "^password" | cut -d '=' -f 2 | xargs)
-_host=$(cat "${_credentials}" | grep "^host" | cut -d '=' -f 2 | xargs)
-_database=$(cat "${_db_file}")
+ssh ${where} "nice -n 19 sh -c 'mysqldump ${options} --user=\"${_user}\" --host=\"${_host}\" --password=\"${_pass}\" ${database} | gzip'" > "${file}"
 
-ssh ${where} "nice -n 19 sh -c 'mysqldump ${options} --user=\"${_user}\" --host=\"${_host}\" --password=\"${_pass}\" ${_database} | gzip'" > "${file}"
+code=${?}
 
-echo "${colored_shortname}Created snapshot ${COLOR_LIGHT_BLUE}${filename}${COLOR_NC}"
-exit 0
+if [ "${code}" -eq 1 ]; then
+  echo "${COLOR_RED}Could not create snapshot ${COLOR_LIGHT_BLUE}${filename}${COLOR_NC}.${COLOR_NC}"
+else
+  echo "${COLOR_GREEN}Created snapshot ${COLOR_LIGHT_BLUE}${filename}${COLOR_NC}${COLOR_NC}"
+fi
+
+exit ${code}
diff --git a/bin/drivers/mysql/connectors/ssh/test b/bin/drivers/mysql/connectors/ssh/test
--- a/bin/drivers/mysql/connectors/ssh/test
+++ b/bin/drivers/mysql/connectors/ssh/test
@@ -1,18 +1,20 @@
 #!/usr/bin/env sh
 
-options="--opt -B --add-drop-database"
+bin=$(dirname "$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]+"/../../../.."))' $0)")
+. "${bin}/include/all"
+
 connection_details="--defaults-extra-file=${connection_config}"
 
-_server=$1
-_config="${repository}/${_server}/config/"
-_credentials="${_config}credentials.cnf"
-_ssh_config="${_config}/ssh.cnf"
-_db_file="${_config}/database"
+where=$(cat "${ssh_config}")
+_user=$(cat "${connection_config}" | grep "^user" | cut -d '=' -f 2 | xargs)
+_pass=$(cat "${connection_config}" | grep "^password" | cut -d '=' -f 2 | xargs)
+_host=$(cat "${connection_config}" | grep "^host" | cut -d '=' -f 2 | xargs)
+ssh ${where} "mysql --user=\"$_user\" --host=\"$_host\" --password=\"$_pass\" -e\"quit\" $database"
+code=${?}
 
-where=`cat "${_ssh_config}"`
-_user=$(cat "${_credentials}" | grep "^user" | cut -d '=' -f 2 | xargs)
-_pass=$(cat "${_credentials}" | grep "^password" | cut -d '=' -f 2 | xargs)
-_host=$(cat "${_credentials}" | grep "^host" | cut -d '=' -f 2 | xargs)
-_database=$(cat "${_db_file}")
-ssh ${where} "mysql --user=\"$_user\" --host=\"$_host\" --password=\"$_pass\" -e\"quit\" $_database"
-exit "${?}"
+if [ "${code}" -eq 1 ]; then
+  echo "${COLOR_RED}Could not connect to database.${COLOR_NC}"
+else
+  echo "${COLOR_GREEN}Successfully connected to database.${COLOR_NC}"
+fi
+exit ${code}
