‘import’ can now import dumps from other servers

diff --git a/bin/include/functions b/bin/include/functions
--- a/bin/include/functions
+++ b/bin/include/functions
@@ -47,3 +47,18 @@ find_snapshot()
     fi
   fi
 }
+
+find_snapshot_from_any_server()
+{
+  snapshot=$1
+  file="${dumps}/${snapshot}.gz"
+
+  if [ ! -f "${file}" ]; then
+    if [ $(find "${repository}" | grep "${snapshot}" | wc -l | sed -e 's/^[[:space:]]*//') -eq 1 ]; then
+      file=$(find "${repository}" | grep "${snapshot}")
+    else
+      echo "${COLOR_LIGHT_BLUE}Provided snapshot name is not unique or does not exist. Aborting.${COLOR_NC}"
+      exit 1
+    fi
+  fi
+}
