Test for existence of mysql binary

diff --git a/bin/drivers/mysql/connectors/direct/test b/bin/drivers/mysql/connectors/direct/test
--- a/bin/drivers/mysql/connectors/direct/test
+++ b/bin/drivers/mysql/connectors/direct/test
@@ -7,8 +7,13 @@ connection_details="--defaults-extra-file=${connection_config}"
 "${mysql}" ${connection_details} -e"quit" >/dev/null
 code=${?}
 
-if [ "${code}" -eq 1 ]; then
-  echo "${COLOR_RED}Could not connect to database.${COLOR_NC}"
+if [ "${code}" -eq 127 ]; then
+  echo "${COLOR_RED}Could not find mysql binary.${COLOR_NC}"
 else
-  echo "${COLOR_GREEN}Successfully connected to database.${COLOR_NC}"
+    if [ "${code}" -eq 1 ]; then
+      echo "${COLOR_RED}Could not connect to database.${COLOR_NC}"
+    else
+      echo "${COLOR_GREEN}Successfully connected to database.${COLOR_NC}"
+    fi
 fi
+exit ${code}
